# NumPy

In [5]:
import numpy as np
import sys
import array

In [7]:
# Типы данных Python
x = 1
print(type(x))
print(sys.getsizeof(x))

<class 'int'>
28


In [9]:
x = 'hello'
print(type(x))

<class 'str'>


In [11]:
x = True
print(type(x))

<class 'bool'>


In [13]:
l1 = list([])
print(sys.getsizeof(l1))

56


In [15]:
l2 = list([1, 2, 3])
print(sys.getsizeof(l2))

88


In [17]:
l3 = list([1, "2", True])
print(l3)

[1, '2', True]


In [19]:
a1 = array.array('i', [1, 2, 3])
print(sys.getsizeof(a1))
print(type(a1))

92
<class 'array.array'>


In [22]:
# Numpy

In [24]:
a = np.array([1, 2, 3, 4, 5])
print(type(a), a)

<class 'numpy.ndarray'> [1 2 3 4 5]


In [26]:
# повыщающее приведение типов
a = np.array([1.23, 2, 3, 4, 5])
print(type(a), a)

<class 'numpy.ndarray'> [1.23 2.   3.   4.   5.  ]


In [28]:
a = np.array([1.23, 2, 3, 4, 5], dtype=int)
print(type(a), a)

<class 'numpy.ndarray'> [1 2 3 4 5]


In [30]:
a = np.array([range(i, i+3) for i in [2, 4, 6]])
print(a, type(a[0]))

[[2 3 4]
 [4 5 6]
 [6 7 8]] <class 'numpy.ndarray'>


In [32]:
a = np.zeros(10, dtype=int)
print(a, type(a))

[0 0 0 0 0 0 0 0 0 0] <class 'numpy.ndarray'>


In [34]:
print(np.ones((3, 5), dtype=float))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [36]:
print(np.full((4, 5), 3.1415))

[[3.1415 3.1415 3.1415 3.1415 3.1415]
 [3.1415 3.1415 3.1415 3.1415 3.1415]
 [3.1415 3.1415 3.1415 3.1415 3.1415]
 [3.1415 3.1415 3.1415 3.1415 3.1415]]


In [38]:
print(np.arange(0, 20, 2))

[ 0  2  4  6  8 10 12 14 16 18]


In [40]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [43]:
### МАССИВЫ 

In [45]:
np.random.seed(1)
x1 = np.random.randint(10, size=3)
x2 = np.random.randint(10, size=(3, 2))
x3 = np.random.randint(10, size=(3, 2, 2))
print(x1)
print(x2)
print(x3)

[5 8 9]
[[5 0]
 [0 1]
 [7 6]]
[[[9 2]
  [4 5]]

 [[2 4]
  [2 4]]

 [[7 7]
  [9 1]]]


In [47]:
print(x1.ndim, x1.shape, x1.size)
print(x2.ndim, x2.shape, x2.size)
print(x3.ndim, x3.shape, x3.size)

1 (3,) 3
2 (3, 2) 6
3 (3, 2, 2) 12


In [49]:
# Индекс (с 0)

In [51]:
a = np.array([1, 2, 3, 4, 5])
print(a[0])
print(a[-2])

1
4


In [53]:
a[1] = 20
print(a)

[ 1 20  3  4  5]


In [55]:
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [57]:
print(a[0, 0])
print(a[-1, -1])

1
4


In [59]:
a[1, 0] = 100
print(a)

[[  1   2]
 [100   4]]


In [61]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4], dtype=float)
print(a)
print(b)

[1 2 3 4]
[1. 2. 3. 4.]


In [63]:
a[0] = 10
print(a)

[10  2  3  4]


In [65]:
a[0] = 10.123
print(a)

[10  2  3  4]


In [67]:
## Срез [s:f:st] [0:shape:1]

In [69]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a[:3:])
print(a[3:])
print(a[1:5])
print(a[1:-1])
print(a[1:6:2])
print(a[1::2])
print(a[::1])
print(a[::-1])

[1 2 3]
[4 5 6]
[2 3 4 5]
[2 3 4 5]
[2 4 6]
[2 4 6]
[1 2 3 4 5 6]
[6 5 4 3 2 1]


In [71]:
b = a[:3]
print(b)

[1 2 3]


In [73]:
b[0] = 100
print(a)

[100   2   3   4   5   6]


In [75]:
a = np.arange(1, 13)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [77]:
print(a.reshape(2, 6))
print(a.reshape(3, 4))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [79]:
x = np.array([1, 2, 3])
y = np.array([4, 5])
z = np.array([6])

print(np.concatenate([x, y, z]))

[1 2 3 4 5 6]


In [81]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

r1 = np.vstack([x, y])
print(r1)

[[1 2 3]
 [4 5 6]]


In [83]:
print(np.hstack([x, y]))

[1 2 3 4 5 6]


In [85]:
### Вычисления с массивами

In [87]:
# Векторизированная операция - независимо к каждому элементу

In [89]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [91]:
print(x * 2 + 1)

[ 1  3  5  7  9 11 13 15 17 19]


In [93]:
# Универсальные функции 

In [95]:
print(np.add(np.multiply(x, 2), 1))

[ 1  3  5  7  9 11 13 15 17 19]


In [97]:
# - - / // ** %
## np.abs, sin/cos/tan, exp, log, sh/ch

In [99]:
x = np.arange(5)
print(np.multiply(x, 10))

[ 0 10 20 30 40]


In [101]:
y = np.empty(10)
print(np.multiply(x, 10, out=y[::2]), y)

[ 0. 10. 20. 30. 40.] [0.0e+000 4.9e-324 1.0e+001 1.5e-323 2.0e+001 2.5e-323 3.0e+001 3.5e-323
 4.0e+001 4.4e-323]


In [103]:
x = np.arange(1, 5)
print(x)
print(np.add.reduce(x))
print(np.add.accumulate(x))

[1 2 3 4]
10
[ 1  3  6 10]


In [105]:
x = np.arange(1, 10)
print(np.add.outer(x, x))

[[ 2  3  4  5  6  7  8  9 10]
 [ 3  4  5  6  7  8  9 10 11]
 [ 4  5  6  7  8  9 10 11 12]
 [ 5  6  7  8  9 10 11 12 13]
 [ 6  7  8  9 10 11 12 13 14]
 [ 7  8  9 10 11 12 13 14 15]
 [ 8  9 10 11 12 13 14 15 16]
 [ 9 10 11 12 13 14 15 16 17]
 [10 11 12 13 14 15 16 17 18]]


In [107]:
print(np.multiply.outer(x, x))

[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]
